apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
  labels:
    name: pv-test
spec:
  storageClassName: nfs
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.1.100
    path: /nfs
